apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-microservice
  namespace: fallsafe-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-microservice
  template:
    metadata:
      labels:
        app: auth-microservice
    spec:
      imagePullSecrets:
        - name: dockerhubsecret
      containers:
        - name: auth-microservice
          image: cheeguang/auth-microservice:latest
          ports:
            - containerPort: 5050
          env:
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: microservices-secret
                  key: AUTH_DB_CONNECTION
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: microservices-secret
                  key: JWT_SECRET
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: microservices-secret
                  key: SMTP_USER
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microservices-secret
                  key: SMTP_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-microservice
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
  type: NodePort
