apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fallsafe-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: dockerhubsecret
      containers:
        - name: frontend
          image: cheeguang/frontend:latest # Replace with your Docker Hub username
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: fallsafe-namespace
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Exposes the service publicly
