apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice
  namespace: fallsafe-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-microservice
  template:
    metadata:
      labels:
        app: user-microservice
    spec:
      imagePullSecrets:
        - name: dockerhubsecret
      containers:
        - name: user-microservice
          image: cheeguang/user-microservice:latest
          ports:
            - containerPort: 5100
          env:
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: microservices-secret
                  key: USER_DB_CONNECTION
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: microservices-secret
                  key: JWT_SECRET
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: microservices-secret
                  key: SMTP_USER
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microservices-secret
                  key: SMTP_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-microservice
  ports:
    - protocol: TCP
      port: 5100
      targetPort: 5100
  type: NodePort
